// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "VCard", Scope = "type", Target = "Fonlow.SyncML.OutlookSync.OutlookContactsWithVCard")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.DeletionLogForContacts+Nested.#.cctor()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1812:AvoidUninstantiatedInternalClasses", Scope = "type", Target = "Fonlow.SyncML.OutlookSync.DeletionLogForContacts+Nested")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1725:ParameterNamesShouldMatchBaseDeclaration", MessageId = "1#", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookToSyncMLSifC.#AddContentToCommand(Fonlow.SyncML.Elements.SyncMLUpdateBase,Microsoft.Office.Interop.Outlook.ContactItem)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1725:ParameterNamesShouldMatchBaseDeclaration", MessageId = "1#", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookToSyncMLVcard.#AddContentToCommand(Fonlow.SyncML.Elements.SyncMLUpdateBase,Microsoft.Office.Interop.Outlook.ContactItem)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookContacts.#.ctor(Microsoft.Office.Interop.Outlook.Application)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookContacts.#DeleteItem(Microsoft.Office.Interop.Outlook.ContactItem)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookContacts.#GetItemName(Microsoft.Office.Interop.Outlook.ContactItem)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookContacts.#GetItemCreationTime(Microsoft.Office.Interop.Outlook.ContactItem)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookContacts.#GetItemLastModificationTime(Microsoft.Office.Interop.Outlook.ContactItem)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookContactsWithSifC.#.ctor(Microsoft.Office.Interop.Outlook.Application)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookContactsWithSifC.#ReadItemToText(Microsoft.Office.Interop.Outlook.ContactItem)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookContactsWithSifC.#WriteMetaToItem(System.String,Microsoft.Office.Interop.Outlook.ContactItem)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookContactsWithVCard.#.ctor(Microsoft.Office.Interop.Outlook.Application)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookContactsWithVCard.#ReadItemToText(Microsoft.Office.Interop.Outlook.ContactItem)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookContactsWithVCard.#WriteMetaToItem(System.String,Microsoft.Office.Interop.Outlook.ContactItem)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookToSyncMLSifC.#AddContentToCommand(Fonlow.SyncML.Elements.SyncMLUpdateBase,Microsoft.Office.Interop.Outlook.ContactItem)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookToSyncMLSifC.#AddContentToCommand(Fonlow.SyncML.Elements.SyncMLUpdateBase,Microsoft.Office.Interop.Outlook.ContactItem)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookToSyncMLVcard.#AddContentToCommand(Fonlow.SyncML.Elements.SyncMLUpdateBase,Microsoft.Office.Interop.Outlook.ContactItem)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookToSyncMLVcard.#AddContentToCommand(Fonlow.SyncML.Elements.SyncMLUpdateBase,Microsoft.Office.Interop.Outlook.ContactItem)")]

