// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.DeletionLogForCalendar+Nested.#.cctor()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1812:AvoidUninstantiatedInternalClasses", Scope = "type", Target = "Fonlow.SyncML.OutlookSync.DeletionLogForCalendar+Nested")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1725:ParameterNamesShouldMatchBaseDeclaration", MessageId = "1#", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookToSyncMLICal.#AddContentToCommand(Fonlow.SyncML.Elements.SyncMLUpdateBase,Microsoft.Office.Interop.Outlook.AppointmentItem)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.DeletionMonitorForCalendar.#.ctor(Microsoft.Office.Interop.Outlook.Application)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookCalendar.#.ctor(Microsoft.Office.Interop.Outlook.Application,Fonlow.SyncML.Common.CalendarPeriod)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookCalendar.#DeleteItem(Microsoft.Office.Interop.Outlook.AppointmentItem)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookCalendar.#GetItemCreationTime(Microsoft.Office.Interop.Outlook.AppointmentItem)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookCalendar.#GetItemLastModificationTime(Microsoft.Office.Interop.Outlook.AppointmentItem)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookCalendar.#GetItemName(Microsoft.Office.Interop.Outlook.AppointmentItem)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookCalendar.#IsItemIncludedInSync(Microsoft.Office.Interop.Outlook.AppointmentItem)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookCalendarWithICal.#ReadItemToText(Microsoft.Office.Interop.Outlook.AppointmentItem)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookCalendarWithICal.#WriteMetaToItem(System.String,Microsoft.Office.Interop.Outlook.AppointmentItem)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookCalendarWithSifE.#ReadItemToText(Microsoft.Office.Interop.Outlook.AppointmentItem)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookCalendarWithSifE.#WriteMetaToItem(System.String,Microsoft.Office.Interop.Outlook.AppointmentItem)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookToSyncMLSifE.#AddContentToCommand(Fonlow.SyncML.Elements.SyncMLUpdateBase,Microsoft.Office.Interop.Outlook.AppointmentItem)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookToSyncMLSifE.#AddContentToCommand(Fonlow.SyncML.Elements.SyncMLUpdateBase,Microsoft.Office.Interop.Outlook.AppointmentItem)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookToSyncMLICal.#AddContentToCommand(Fonlow.SyncML.Elements.SyncMLUpdateBase,Microsoft.Office.Interop.Outlook.AppointmentItem)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookToSyncMLICal.#AddContentToCommand(Fonlow.SyncML.Elements.SyncMLUpdateBase,Microsoft.Office.Interop.Outlook.AppointmentItem)")]

