// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1725:ParameterNamesShouldMatchBaseDeclaration", MessageId = "1#", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookToSyncMLSifT.#AddContentToCommand(Fonlow.SyncML.Elements.SyncMLUpdateBase,Microsoft.Office.Interop.Outlook.TaskItem)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.DeletionLogForTasks+Nested.#.cctor()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1812:AvoidUninstantiatedInternalClasses", Scope = "type", Target = "Fonlow.SyncML.OutlookSync.DeletionLogForTasks+Nested")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1725:ParameterNamesShouldMatchBaseDeclaration", MessageId = "1#", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookToSyncMLTodo.#AddContentToCommand(Fonlow.SyncML.Elements.SyncMLUpdateBase,Microsoft.Office.Interop.Outlook.TaskItem)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.DeletionMonitorForTasks.#.ctor(Microsoft.Office.Interop.Outlook.Application)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookTasks.#.ctor(Microsoft.Office.Interop.Outlook.Application)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookTasks.#DeleteItem(Microsoft.Office.Interop.Outlook.TaskItem)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookTasks.#GetItemCreationTime(Microsoft.Office.Interop.Outlook.TaskItem)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookTasks.#GetItemLastModificationTime(Microsoft.Office.Interop.Outlook.TaskItem)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookTasks.#GetItemName(Microsoft.Office.Interop.Outlook.TaskItem)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookTasksWithICal.#ReadItemToText(Microsoft.Office.Interop.Outlook.TaskItem)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookTasksWithICal.#WriteMetaToItem(System.String,Microsoft.Office.Interop.Outlook.TaskItem)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookTasksWithSifT.#ReadItemToText(Microsoft.Office.Interop.Outlook.TaskItem)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookTasksWithSifT.#WriteMetaToItem(System.String,Microsoft.Office.Interop.Outlook.TaskItem)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookToSyncMLSifT.#AddContentToCommand(Fonlow.SyncML.Elements.SyncMLUpdateBase,Microsoft.Office.Interop.Outlook.TaskItem)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookToSyncMLSifT.#AddContentToCommand(Fonlow.SyncML.Elements.SyncMLUpdateBase,Microsoft.Office.Interop.Outlook.TaskItem)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookToSyncMLTodo.#AddContentToCommand(Fonlow.SyncML.Elements.SyncMLUpdateBase,Microsoft.Office.Interop.Outlook.TaskItem)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookToSyncMLTodo.#AddContentToCommand(Fonlow.SyncML.Elements.SyncMLUpdateBase,Microsoft.Office.Interop.Outlook.TaskItem)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookTasksWithSifT.#GetEntryId(Microsoft.Office.Interop.Outlook.TaskItem)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.DeletionMonitorForTasks.#GetItemEntryId(Microsoft.Office.Interop.Outlook.TaskItem)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookTasks.#GetEntryId(Microsoft.Office.Interop.Outlook.TaskItem)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Fonlow.SyncML.OutlookSync.OutlookTasksWithICal.#GetEntryId(Microsoft.Office.Interop.Outlook.TaskItem)")]

