//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fonlow.SyncML.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fonlow.SyncML.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DataStore&gt;&lt;SourceRef&gt;scard&lt;/SourceRef&gt;&lt;DisplayName&gt;Sif-C Source&lt;/DisplayName&gt;&lt;Rx-Pref&gt;&lt;CTType&gt;text/x-s4j-sifc&lt;/CTType&gt;&lt;VerCT&gt;&lt;/VerCT&gt;&lt;/Rx-Pref&gt;&lt;Rx&gt;
        ///&lt;CTType&gt;text/x-s4j-sifc&lt;/CTType&gt;&lt;VerCT&gt;&lt;/VerCT&gt;&lt;/Rx&gt;&lt;Tx-Pref&gt;&lt;CTType&gt;text/x-s4j-sifc&lt;/CTType&gt;&lt;VerCT&gt;&lt;/VerCT&gt;
        ///&lt;/Tx-Pref&gt;&lt;Tx&gt;&lt;CTType&gt;text/x-s4j-sifc&lt;/CTType&gt;&lt;VerCT&gt;&lt;/VerCT&gt;&lt;/Tx&gt;&lt;SyncCap&gt;&lt;SyncType&gt;1&lt;/SyncType&gt;&lt;SyncType&gt;2&lt;/SyncType&gt;
        ///&lt;SyncType&gt;3&lt;/SyncType&gt;&lt;SyncType&gt;4&lt;/SyncType&gt;&lt;SyncType&gt;5&lt;/SyncType&gt;&lt;SyncType&gt;6&lt;/SyncType&gt;&lt;/SyncCap&gt;&lt;/DataStore&gt;.
        /// </summary>
        internal static string DataStoreSIFC {
            get {
                return ResourceManager.GetString("DataStoreSIFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DataStore&gt;
        ///&lt;SourceRef&gt;card&lt;/SourceRef&gt;
        ///&lt;DisplayName&gt;vCardSource&lt;/DisplayName&gt;
        ///&lt;Rx-Pref&gt;
        ///&lt;CTType&gt;text/x-vcard&lt;/CTType&gt;
        ///&lt;VerCT&gt;2.1&lt;/VerCT&gt;
        ///&lt;/Rx-Pref&gt;
        ///&lt;Rx&gt;
        ///&lt;CTType&gt;text/x-vcard&lt;/CTType&gt;
        ///&lt;VerCT&gt;2.1&lt;/VerCT&gt;
        ///&lt;/Rx&gt;
        ///&lt;Tx-Pref&gt;
        ///&lt;CTType&gt;text/x-vcard&lt;/CTType&gt;
        ///&lt;VerCT&gt;2.1&lt;/VerCT&gt;
        ///&lt;/Tx-Pref&gt;
        ///&lt;Tx&gt;
        ///&lt;CTType&gt;text/x-vcard&lt;/CTType&gt;
        ///&lt;VerCT&gt;2.1&lt;/VerCT&gt;
        ///&lt;/Tx&gt;
        ///&lt;CTCap&gt;
        ///&lt;CTType&gt;text/x-vcard&lt;/CTType&gt;
        ///&lt;VerCT&gt;2.1&lt;/VerCT&gt;
        ///&lt;Property&gt;
        ///&lt;PropName&gt;BEGIN&lt;/PropName&gt;
        ///&lt;ValEnum&gt;VCARD&lt;/ValEnum&gt;
        ///&lt;/Property&gt;
        ///&lt;Property&gt;
        ///&lt;Pr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataStoreVCard21 {
            get {
                return ResourceManager.GetString("DataStoreVCard21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200=OK. The SyncML command completed successfully.
        ///201=Item added. The requested item was added.
        ///202=Accepted for processing. The request to either run a remote execution of an application or to alert a user or application was successfully performed.
        ///203=Non-authoritative response. The request is being responded to by an entity other than the one targeted. The response is only to be returned when the request would have been resulted in a 200 response code from the authoritative target.
        ///204=No content. T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StatusMessages {
            get {
                return ResourceManager.GetString("StatusMessages", resourceCulture);
            }
        }
    }
}
